name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # IMPORTANT: Ensure this matches your default branch name (e.g., 'main' or 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version
          cache: 'npm'

      - name: Clean install dependencies (in jobpalace project)
        run: |
          npm cache clean --force # Ensure cache is clean
          rm -rf node_modules package-lock.json # Remove both to force fresh install
          npm install --unsafe-perm=true --allow-root # Install with options for native modules
        working-directory: jobpalace # CRITICAL: Run this step inside 'jobpalace'

      - name: Build project
        run: npm run build # Use the reverted build script
        working-directory: jobpalace # CRITICAL: Run this step inside 'jobpalace'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jobpalace/dist # Still relative to the repository root
          publish_branch: gh-pages